import { store } from '../state/store.js';
import { col,getDocs,ref,setDoc,serverTimestamp } from '../data/firestore.js';
import { esc,toast,modal,$ } from '../utils/dom.js';
import { createGraderAccount,resetGraderPassword,deleteGraderAccount } from '../services/graderAccounts.js';
export async function renderGraders(){const view=$('#view'),snap=await getDocs(col('users')),graders=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.role==='Grader'),groups=[...store.get().groups.values()];view.innerHTML=`<div class="toolbar"><div><h3 style="margin:0">Quản lý Giám khảo</h3><div class="tiny muted">Firebase Auth riêng cho từng BGK.</div></div><button class="btn primary" id="new-grader">+ Tạo tài khoản BGK</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Mã</th><th>Tên</th><th>Nhóm</th><th>Auth</th><th>Thao tác</th></tr></thead><tbody>${graders.map(g=>`<tr><td>${esc(g.code)}</td><td>${esc(g.name)}</td><td>${(g.assignedGroups||[]).map(id=>esc(store.get().groups.get(id)?.name||id)).join(', ')}</td><td>${g.authUid?'<span class="badge ok">Firebase Auth</span>':'<span class="badge warn">Legacy</span>'}</td><td><button class="btn small" data-edit="${g.id}">Phân quyền</button> ${g.authUid?`<button class="btn small" data-reset="${g.id}">Đổi mật khẩu</button>`:`<button class="btn small ok" data-migrate="${g.id}">Kích hoạt Auth</button>`}</td></tr>`).join('')}</tbody></table></div>`;$('#new-grader').onclick=()=>newGrader(groups);view.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editAssigned(graders.find(x=>x.id===b.dataset.edit),groups));view.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>resetPassword(graders.find(x=>x.id===b.dataset.reset)));view.querySelectorAll('[data-migrate]').forEach(b=>b.onclick=()=>migrateLegacy(graders.find(x=>x.id===b.dataset.migrate)))}
function newGrader(groups){const root=modal({title:'Tạo tài khoản BGK',body:`<label class="label">Mã BGK</label><input id="ng-code" class="input" placeholder="GS-XXXX"><label class="label" style="margin-top:10px">Tên</label><input id="ng-name" class="input"><label class="label" style="margin-top:10px">Mật khẩu tạm</label><input id="ng-pass" class="input" type="password"><div style="margin-top:12px">${groups.map(g=>`<label style="display:block;margin:7px 0"><input type="checkbox" class="ng-group" value="${g.id}"> ${esc(g.name)}</label>`).join('')}</div>`,actions:`<span></span><div><button class="btn" data-close>Hủy</button> <button class="btn primary" id="ng-save">Tạo</button></div>`});root.querySelector('#ng-save').onclick=async()=>{try{const assignedGroups=[...root.querySelectorAll('.ng-group:checked')].map(x=>x.value);await createGraderAccount({code:root.querySelector('#ng-code').value.trim(),name:root.querySelector('#ng-name').value.trim(),password:root.querySelector('#ng-pass').value,assignedGroups});root.innerHTML='';toast('Đã tạo tài khoản Firebase Auth cho BGK');renderGraders()}catch(e){toast(e.message,'error')}}}
function editAssigned(g,groups){const root=modal({title:`Phân quyền ${g.name}`,body:groups.map(x=>`<label style="display:block;margin:8px 0"><input type="checkbox" class="eg" value="${x.id}" ${(g.assignedGroups||[]).includes(x.id)?'checked':''}> ${esc(x.name)}</label>`).join(''),actions:`<span></span><div><button class="btn" data-close>Hủy</button> <button class="btn primary" id="eg-save">Lưu</button></div>`});root.querySelector('#eg-save').onclick=async()=>{const assignedGroups=[...root.querySelectorAll('.eg:checked')].map(x=>x.value);await setDoc(ref('users',g.id),{assignedGroups,permissionsVersion:Date.now(),permissionsUpdatedAt:serverTimestamp()},{merge:true});root.innerHTML='';toast('Đã cập nhật phân quyền realtime');renderGraders()}}
function resetPassword(g){const p=prompt(`Mật khẩu mới cho ${g.code}:`);if(!p)return;resetGraderPassword({uid:g.authUid||g.id,password:p}).then(()=>toast('Đã đổi mật khẩu')).catch(e=>toast(e.message,'error'))}

function migrateLegacy(g){const p=prompt(`Mật khẩu tạm cho ${g.code}:`);if(!p)return;createGraderAccount({code:g.code,name:g.name,password:p,assignedGroups:g.assignedGroups||[],legacyUserId:g.id}).then(()=>{toast('Đã chuyển BGK sang Firebase Auth riêng');renderGraders()}).catch(e=>toast(e.message,'error'))}
