import { normalizeContent,defaultColumns } from '../services/content.js';
import { ref,setDoc,serverTimestamp } from '../data/firestore.js';
import { modal,esc,toast } from '../utils/dom.js';

export function openContentEditor(group){const cfg=normalizeContent(group);const root=modal({title:`Nội dung chấm & phỏng vấn – ${group.name}`,body:`<div class="tabs"><button class="active" data-ctab="scoring">Tiêu chí chấm</button><button data-ctab="interview">Câu hỏi phỏng vấn</button></div><section id="content-scoring" style="margin-top:16px">${scoringEditor(cfg.scoringContent)}</section><section id="content-interview" class="hidden" style="margin-top:16px">${interviewEditor(cfg.interviewContent)}</section>`,actions:`<span class="tiny muted">Dữ liệu lưu theo schema contentConfig V2, tương thích dữ liệu V27.</span><div><button class="btn" data-close>Hủy</button> <button class="btn primary" id="content-save">Lưu tất cả</button></div>`});
  root.querySelectorAll('[data-ctab]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-ctab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelector('#content-scoring').classList.toggle('hidden',b.dataset.ctab!=='scoring');root.querySelector('#content-interview').classList.toggle('hidden',b.dataset.ctab!=='interview')});
  bindScoring(root);bindInterview(root);
  root.querySelector('#content-save').onclick=async()=>{try{const contentConfig={scoringContent:readScoring(root),interviewContent:readInterview(root)};await setDoc(ref('competition_groups',group.id),{contentConfig,contentSchemaVersion:2,contentUpdatedAt:serverTimestamp()},{merge:true});root.innerHTML='';toast('Đã lưu nội dung tiêu chí và câu hỏi')}catch(e){toast(e.message,'error')}};
}
function scoringEditor(sc){return `<div class="grid grid-3"><label><span class="label">Bật phần này</span><select id="sc-enabled" class="select"><option value="1" ${sc.enabled?'selected':''}>Bật</option><option value="0" ${!sc.enabled?'selected':''}>Tắt</option></select></label><label><span class="label">Thời điểm mở</span><select id="sc-mode" class="select"><option value="group" ${sc.mode==='group'?'selected':''}>Khi nhóm mở</option><option value="before" ${sc.mode==='before'?'selected':''}>Mở trước giờ nhóm</option></select></label><label><span class="label">Tiêu đề</span><input id="sc-title" class="input" value="${esc(sc.title)}"></label></div><div class="toolbar" style="margin-top:14px"><strong>Bảng tiêu chí</strong><div class="right"><button class="btn small" id="sc-add-col">+ Cột</button><button class="btn small" id="sc-add-row">+ Dòng</button></div></div><div class="table-wrap"><table class="table" id="sc-table"><thead><tr>${sc.columns.map(c=>`<th><input class="input sc-col-label" data-key="${esc(c.key)}" data-type="${esc(c.type||'text')}" value="${esc(c.label)}" style="min-width:140px"></th>`).join('')}<th></th></tr></thead><tbody>${sc.rows.map(r=>scoreRow(sc.columns,r)).join('')}</tbody></table></div>`}
function scoreRow(cols,r={id:crypto.randomUUID(),cells:{}}){return `<tr data-rowid="${r.id}">${cols.map(c=>`<td>${c.type==='textarea'?`<textarea class="textarea sc-cell" data-key="${esc(c.key)}">${esc(r.cells?.[c.key]??'')}</textarea>`:`<input class="input sc-cell" data-key="${esc(c.key)}" type="${['number','percent'].includes(c.type)?'number':'text'}" value="${esc(r.cells?.[c.key]??'')}">`}</td>`).join('')}<td><button class="btn small danger sc-del-row">×</button></td></tr>`}
function bindScoring(root){const table=()=>root.querySelector('#sc-table');root.querySelector('#sc-add-row').onclick=()=>{const cols=readColumns(root),tb=table().querySelector('tbody');tb.insertAdjacentHTML('beforeend',scoreRow(cols));bindRowDeletes(root)};root.querySelector('#sc-add-col').onclick=()=>{const label=prompt('Tên cột mới:');if(!label)return;const key=`col_${Date.now()}`;const th=`<th><input class="input sc-col-label" data-key="${key}" data-type="text" value="${esc(label)}" style="min-width:140px"></th>`;table().querySelector('thead tr th:last-child').insertAdjacentHTML('beforebegin',th);table().querySelectorAll('tbody tr').forEach(tr=>tr.querySelector('td:last-child').insertAdjacentHTML('beforebegin',`<td><input class="input sc-cell" data-key="${key}"></td>`))};bindRowDeletes(root)}
function bindRowDeletes(root){root.querySelectorAll('.sc-del-row').forEach(b=>b.onclick=()=>b.closest('tr').remove())}
function readColumns(root){return[...root.querySelectorAll('.sc-col-label')].map(i=>({key:i.dataset.key,label:i.value.trim()||i.dataset.key,type:i.dataset.type||'text'}))}
function readScoring(root){const columns=readColumns(root),rows=[...root.querySelectorAll('#sc-table tbody tr')].map((tr,i)=>{const cells={};tr.querySelectorAll('.sc-cell').forEach(x=>cells[x.dataset.key]=x.value.trim());if(cells.stt===''||cells.stt===undefined)cells.stt=String(i+1);return{id:tr.dataset.rowid||crypto.randomUUID(),cells}}).filter(r=>Object.values(r.cells).some(Boolean));return{enabled:root.querySelector('#sc-enabled').value==='1',mode:root.querySelector('#sc-mode').value,title:root.querySelector('#sc-title').value.trim()||'TIÊU CHÍ CHẤM ĐIỂM',columns,rows}}
function interviewEditor(iv){return `<div class="grid grid-3"><label><span class="label">Bật phần này</span><select id="iv-enabled" class="select"><option value="1" ${iv.enabled?'selected':''}>Bật</option><option value="0" ${!iv.enabled?'selected':''}>Tắt</option></select></label><label><span class="label">Thời điểm mở</span><select id="iv-mode" class="select"><option value="group" ${iv.mode==='group'?'selected':''}>Khi nhóm mở</option><option value="before" ${iv.mode==='before'?'selected':''}>Mở trước giờ nhóm</option></select></label><label><span class="label">Tiêu đề</span><input id="iv-title" class="input" value="${esc(iv.title)}"></label></div><div class="toolbar" style="margin-top:14px"><strong>Dạng câu hỏi</strong><button class="btn small" id="iv-add-type">+ Thêm dạng</button></div><div id="iv-types">${iv.groups.map(interviewType).join('')}</div>`}
function interviewType(g={id:crypto.randomUUID(),title:'Dạng câu hỏi',description:'',questions:[]}){return `<div class="card pad iv-type" data-id="${g.id}" style="margin-bottom:12px"><div class="toolbar"><input class="input iv-title" value="${esc(g.title)}" style="max-width:420px"><button class="btn small danger iv-del-type">Xóa dạng</button></div><textarea class="textarea iv-desc" placeholder="Mô tả dạng">${esc(g.description||'')}</textarea><div class="iv-questions">${(g.questions||[]).map(questionRow).join('')}</div><button class="btn small iv-add-q" style="margin-top:9px">+ Câu hỏi</button></div>`}
function questionRow(q={id:crypto.randomUUID(),text:'',note:''}){return `<div class="grid grid-2 iv-question" data-id="${q.id}" style="margin-top:9px"><textarea class="textarea iv-q" placeholder="Câu hỏi">${esc(q.text)}</textarea><div><textarea class="textarea iv-note" placeholder="Gợi ý / lưu ý">${esc(q.note||'')}</textarea><button class="btn small danger iv-del-q">Xóa câu</button></div></div>`}
function bindInterview(root){const bind=()=>{root.querySelectorAll('.iv-del-type').forEach(b=>b.onclick=()=>b.closest('.iv-type').remove());root.querySelectorAll('.iv-add-q').forEach(b=>b.onclick=()=>{b.closest('.iv-type').querySelector('.iv-questions').insertAdjacentHTML('beforeend',questionRow());bind()});root.querySelectorAll('.iv-del-q').forEach(b=>b.onclick=()=>b.closest('.iv-question').remove())};root.querySelector('#iv-add-type').onclick=()=>{root.querySelector('#iv-types').insertAdjacentHTML('beforeend',interviewType());bind()};bind()}
function readInterview(root){const groups=[...root.querySelectorAll('.iv-type')].map((el,i)=>({id:el.dataset.id||crypto.randomUUID(),title:el.querySelector('.iv-title').value.trim()||`Dạng ${i+1}`,description:el.querySelector('.iv-desc').value.trim(),questions:[...el.querySelectorAll('.iv-question')].map(q=>({id:q.dataset.id||crypto.randomUUID(),text:q.querySelector('.iv-q').value.trim(),note:q.querySelector('.iv-note').value.trim()})).filter(q=>q.text||q.note)})).filter(g=>g.title||g.questions.length);return{enabled:root.querySelector('#iv-enabled').value==='1',mode:root.querySelector('#iv-mode').value,title:root.querySelector('#iv-title').value.trim()||'CÂU HỎI PHỎNG VẤN',groups}}
