import { loginAdmin,loginGrader } from '../auth/auth.js';
import { toast,$ } from '../utils/dom.js';
export function renderLogin(onSuccess){
  document.querySelector('#app').innerHTML=`<div class="login-wrap"><div class="login-shell">
    <section class="login-visual"><div><div class="visual-mark">G</div><h1>GradeSync</h1><p>Hệ thống chấm điểm trực tiếp dành cho Ban tổ chức và Giám khảo. Dữ liệu được đồng bộ theo thời gian thực giữa các thiết bị.</p><div class="feature-mini"><div><i class="fa-solid fa-bolt"></i> Đồng bộ điểm và điểm danh tức thời</div><div><i class="fa-solid fa-shield-halved"></i> Phân quyền riêng cho từng tài khoản</div><div><i class="fa-solid fa-cloud-arrow-up"></i> Hỗ trợ lưu điểm khi mất kết nối</div></div></div><div class="tiny" style="color:#efc6c8">Our Stage · GradeSync</div></section>
    <section class="login-card"><h2>Đăng nhập hệ thống</h2><div class="login-note">Chọn đúng loại tài khoản để truy cập giao diện phù hợp.</div><div class="login-switch"><button id="tab-admin" class="active">Quản trị viên</button><button id="tab-grader">Giám khảo</button></div>
      <form id="admin-form"><label class="label">Email quản trị</label><input class="input" id="admin-email" type="email" autocomplete="email" placeholder="email@domain.com" required><label class="label" style="margin-top:12px">Mật khẩu</label><input class="input" id="admin-pass" type="password" autocomplete="current-password" placeholder="Nhập mật khẩu" required><button class="btn primary" style="width:100%;margin-top:16px"><i class="fa-solid fa-right-to-bracket"></i> Đăng nhập quản trị</button><div class="login-help"><b>Lưu ý:</b> Tài khoản phải được cấp quyền Admin hoặc SuperAdmin trong hệ thống.</div></form>
      <form id="grader-form" class="hidden"><label class="label">Mã giám khảo</label><input class="input" id="grader-code" placeholder="GS-XXXX" autocomplete="username" required><label class="label" style="margin-top:12px">Mật khẩu</label><input class="input" id="grader-pass" type="password" autocomplete="current-password" placeholder="Mật khẩu do Admin cấp" required><button class="btn primary" style="width:100%;margin-top:16px"><i class="fa-solid fa-pen-to-square"></i> Vào giao diện chấm</button><div class="login-help">Mỗi giám khảo có tài khoản riêng. Nhóm chấm được phân quyền sẽ tự đồng bộ ngay sau khi đăng nhập.</div></form>
    </section></div></div>`;
  const switchTab=grader=>{$('#tab-admin').classList.toggle('active',!grader);$('#tab-grader').classList.toggle('active',grader);$('#admin-form').classList.toggle('hidden',grader);$('#grader-form').classList.toggle('hidden',!grader)};
  $('#tab-admin').onclick=()=>switchTab(false);$('#tab-grader').onclick=()=>switchTab(true);
  $('#admin-form').onsubmit=async e=>{e.preventDefault();try{onSuccess(await loginAdmin($('#admin-email').value,$('#admin-pass').value))}catch(err){toast(err.message,'error')}};
  $('#grader-form').onsubmit=async e=>{e.preventDefault();try{onSuccess(await loginGrader($('#grader-code').value,$('#grader-pass').value))}catch(err){toast(err.message,'error')}};
}
