import { store } from '../state/store.js';
import { esc,toast,$ } from '../utils/dom.js';
import { setEmergencyLock } from '../services/system.js';
import { ref,setDoc,serverTimestamp } from '../data/firestore.js';
export function renderLiveMonitor(){
  const st=store.get(),view=$('#view'),presence=[...st.presence.values()],now=Date.now();
  view.innerHTML=`<div class="toolbar"><div><div class="tiny muted">GIÁM SÁT THỜI GIAN THỰC</div><h3 style="margin:3px 0 0">Theo dõi giám khảo trực tiếp</h3><div class="tiny muted" style="margin-top:4px">Theo dõi kết nối, thí sinh đang chấm, tiến độ và trạng thái nộp của từng giám khảo.</div></div><div class="right">${st.system.emergencyLock?'<button class="btn ok" id="unlock-all"><i class="fa-solid fa-lock-open"></i> Mở khóa hệ thống</button>':'<button class="btn danger" id="lock-all"><i class="fa-solid fa-triangle-exclamation"></i> KHÓA KHẨN CẤP</button>'}</div></div><div class="grid grid-3">${presence.map(p=>{const t=p.lastSeen?.toMillis?.()||0,online=p.state==='online'&&now-t<60000,c=st.candidates.get(p.candidateId),g=st.groups.get(p.groupId),groupCandidates=[...st.candidates.values()].filter(x=>x.groupId===p.groupId&&(!g?.attendanceEnabled||x.isPresent)),ownScores=[...st.scores.values()].filter(s=>s.groupId===p.groupId&&s.graderUid===p.graderUid),progress=groupCandidates.length?Math.min(100,ownScores.length/groupCandidates.length*100):0,submitted=[...st.verifications.values()].some(v=>v.groupId===p.groupId&&v.graderUid===p.graderUid&&v.isVerified),lastScore=ownScores.map(x=>x.updatedAt?.toMillis?.()||0).sort((a,b)=>b-a)[0]||0;return`<div class="card pad"><div class="toolbar"><div><strong>${esc(p.graderName||p.graderCode)}</strong><div class="tiny muted">${esc(p.graderCode||'')}</div></div><span class="badge ${online?'ok':'danger'}">${online?'Trực tuyến':'Mất kết nối'}</span></div><div class="tiny">Nhóm: <b>${esc(g?.name||'-')}</b></div><div class="tiny" style="margin-top:5px">Đang chấm: <b>${esc(c?.name||'-')}</b></div><div style="margin-top:12px"><div class="tiny muted">Tiến độ ${progress.toFixed(0)}% · ${ownScores.length}/${groupCandidates.length}</div><div class="progress"><span style="width:${progress}%"></span></div></div><div style="margin-top:10px;display:flex;gap:7px;flex-wrap:wrap"><span class="badge ${submitted?'ok':'gray'}">${submitted?'Đã nộp':'Chưa nộp'}</span>${submitted?`<button class="btn small" data-unlock-ver="${p.graderUid}|${p.groupId}">Mở khóa nộp</button>`:''}<span class="badge gray">Lưu điểm gần nhất: ${lastScore?new Date(lastScore).toLocaleTimeString('vi-VN'):'-'}</span></div><div class="tiny muted" style="margin-top:10px">Cập nhật kết nối: ${t?new Date(t).toLocaleTimeString('vi-VN'):'-'}</div></div>`}).join('')||'<div class="card pad muted">Chưa có dữ liệu kết nối của giám khảo.</div>'}</div>`;
  if($('#lock-all'))$('#lock-all').onclick=async()=>{const reason=prompt('Lý do khóa khẩn cấp:')||'Khóa bởi quản trị viên';await setEmergencyLock(true,reason,st.user);toast('Đã khóa toàn hệ thống','error')};
  if($('#unlock-all'))$('#unlock-all').onclick=async()=>{await setEmergencyLock(false,'',st.user);toast('Đã mở lại hệ thống')};
  view.querySelectorAll('[data-unlock-ver]').forEach(b=>b.onclick=async()=>{const [uid,gid]=b.dataset.unlockVer.split('|');await setDoc(ref('grader_verifications',`${uid}_${gid}`),{graderUid:uid,groupId:gid,isVerified:false,unlockedAt:serverTimestamp(),unlockedBy:st.user.name||st.user.email||''},{merge:true});toast('Đã mở khóa nộp cho giám khảo')});
}
