import { downloadBlob } from '../utils/dom.js';
import { councilAverage } from '../utils/scoring.js';
function reportId(groupId,graderCode='COUNCIL'){const d=new Date();const stamp=d.toISOString().replace(/[-:TZ.]/g,'').slice(0,14);return `GS-${String(groupId).slice(0,8).toUpperCase()}-${String(graderCode).replace(/[^A-Z0-9_-]/gi,'').toUpperCase()}-${stamp}`}
async function logoDataUrl(settings){return settings?.reportLogoDataUrl||null}
export async function buildGraderPdf({group,candidates,scores,grader,settings={}}){const {jsPDF}=window.jspdf;const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});const rid=reportId(group.id,grader.code);const logo=await logoDataUrl(settings);if(logo){try{doc.addImage(logo,'PNG',12,10,18,18)}catch{}}
  doc.setFontSize(15);doc.text(settings.reportTitle||'BIÊN BẢN CHẤM',148,15,{align:'center'});doc.setFontSize(9);doc.text(`Nhóm: ${group.name}`,12,34);doc.text(`Giám khảo: ${grader.name} - ${grader.code}`,12,40);doc.text(`Mã biên bản: ${rid}`,12,46);
  const cols=['STT','SBD','Họ tên',...(group.criteria||[]).map(c=>`${c.name} (${c.weight}%)`),'Tổng','Kết quả'];
  const rows=candidates.map((c,i)=>{const s=scores.find(x=>x.candidateId===c.id&&x.graderUid===grader.authUid)||{};return[i+1,c.code,c.name,...(group.criteria||[]).map(cr=>s.scores?.[cr.name]??''),s.totalScore??'',s.candidateId?(Number(s.totalScore)>=Number(group.passScore)?'ĐẠT':'TRƯỢT'):'CHỜ']});
  doc.autoTable({head:[cols],body:rows,startY:52,styles:{fontSize:7,cellPadding:2}});const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setFontSize(7);doc.text(`Trang ${i}/${pages}`,285,202,{align:'right'});doc.text(rid,12,202)}return{doc,rid}
}
export async function exportGraderPdf(args){const {doc,rid}=await buildGraderPdf(args);doc.save(`${rid}.pdf`)}
export async function exportAllGradersZip({group,candidates,scores,graders,settings={}}){const zip=new window.JSZip();for(const g of graders){const {doc,rid}=await buildGraderPdf({group,candidates,scores,grader:g,settings});zip.file(`${rid}.pdf`,doc.output('arraybuffer'))}const blob=await zip.generateAsync({type:'blob'});downloadBlob(blob,`GradeSync_${group.name}_BienBanBGK.zip`)}
export function exportCouncilExcel({group,candidates,scores,graders}){const wb=window.XLSX.utils.book_new();for(const criterion of group.criteria||[]){const rows=candidates.map((c,i)=>{const obj={STT:i+1,SBD:c.code,'Họ tên':c.name};const vals=[];for(const g of graders){const s=scores.find(x=>x.candidateId===c.id&&x.graderUid===g.authUid);const v=s?.scores?.[criterion.name];obj[g.code]=v??'';if(Number.isFinite(Number(v)))vals.push(Number(v))}obj['TB Hội đồng']=vals.length?Number((vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(2)):'';return obj});window.XLSX.utils.book_append_sheet(wb,window.XLSX.utils.json_to_sheet(rows),String(criterion.name).slice(0,31))}window.XLSX.writeFile(wb,`GradeSync_${group.name}_HoiDong.xlsx`)}
export {reportId};
